# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpiceEdit < Formula
  desc "SpiceEdit — opinionated mouse-first terminal code editor."
  homepage "https://github.com/cloudmanic/spice-edit"
  version "0.0.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudmanic/spice-edit/releases/download/v0.0.23/spiceedit_0.0.23_darwin_amd64.tar.gz"
      sha256 "08ae3f3c11bb5da8ad8ffa5ebb4b29797cd81fcc79edf1dacc09331d65e14e8f"

      define_method(:install) do
        bin.install "spiceedit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudmanic/spice-edit/releases/download/v0.0.23/spiceedit_0.0.23_darwin_arm64.tar.gz"
      sha256 "6a264bab19ef509f81acc64e6d12e40e9f5a1bf5e1b129438c21216103fa3ef7"

      define_method(:install) do
        bin.install "spiceedit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudmanic/spice-edit/releases/download/v0.0.23/spiceedit_0.0.23_linux_amd64.tar.gz"
      sha256 "07b65775912d6852fddcefc9e10c723729fbfa19b284ab0dc36cb2cbfd552d66"
      define_method(:install) do
        bin.install "spiceedit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudmanic/spice-edit/releases/download/v0.0.23/spiceedit_0.0.23_linux_arm64.tar.gz"
      sha256 "eac8d8cd2910bba4e5bb50710822f1ff3aec021c0e94dbdee225403e3edaad75"
      define_method(:install) do
        bin.install "spiceedit"
      end
    end
  end

  test do
    assert_path_exists bin/"spiceedit"
  end
end
